services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_server
    user: root
    ports:
      - "8080:8080"        # Interface web de Jenkins
      - "50000:50000"      # Communication avec les agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Pour exécuter Docker depuis Jenkins
    networks:
      - app-network
    restart: unless-stopped

volumes:
  jenkins_home:

networks:
  app-network:
    driver: bridge
