pipeline {
    agent {
        label 'windows' // Utiliser un agent Windows
    }
    environment {
        DOCKER_USERNAME = "faliloumfd"
        IMAGE_VERSION = "1.${BUILD_NUMBER}"
        // DOCKER_IMAGE = "${DOCKER_USERNAME}/gestion_presence_app:${IMAGE_VERSION}"
        DOCKER_IMAGE = "faliloumfd/gestion_presence_app:latest" // Nom de l'image Docker
        DOCKER_CONTAINER = "gestion_presence_app"
    }

    stages {
        stage("Checkout") {
            steps {
                git branch: 'master', url: 'https://github.com/Falilou-MFD/ges_abs_ret.git'
            }
        }

        stage("Test") {
            steps {
                echo "Tests en cours"
                // Ajouter ici des scripts de test selon le type d'environnement
            }
        }

        stage("Build Docker Image") {
            steps {
                script {
                    bat "docker build -t ${DOCKER_IMAGE} gestion_presence_app"
                }
            }
        }

        stage("Push image to Docker Hub") {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'faliloumfd1', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWORD')]) {
                        bat """
                            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USER}" --password-stdin
                            echo "Docker login successful"
                            docker push ${DOCKER_IMAGE}
                        """
                    }
                }
            }
        }

        stage("Deploy") {
            steps {
                script {
                    bat """
                        docker container stop ${DOCKER_CONTAINER} || true
                        docker container rm ${DOCKER_CONTAINER} || true
                        docker run -d --name ${DOCKER_CONTAINER} -p 8080:80 ${DOCKER_IMAGE}
                    """
                }
            }
        }
    }

    post {
        success {
            mail to: 'mancabouben12@gmail.com, falilou1999@gmail.com, maimounasow1410@gmail.com, kubuyaphilemon4@gmail.com, robinyonli2@gmail.com',
                 subject: "✅ Succès du pipeline : ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: "Le pipeline a été exécuté avec succès.\nVoir les détails ici : ${env.BUILD_URL}"
        }

        failure {
            mail to: 'mancabouben12@gmail.com, falilou1999@gmail.com, maimounasow1410@gmail.com, kubuyaphilemon4@gmail.com, robinyonli2@gmail.com',
                 subject: "❌ Échec du pipeline : ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: "Le pipeline a échoué.\nVoir les logs ici : ${env.BUILD_URL}"
        }

        always {
            echo 'Notification e-mail envoyée.'
        }
    }
}
